-- 5Tap Supabase architecture
-- Run this in Supabase SQL Editor, then set these Site environment variables:
-- SUPABASE_URL=https://YOUR-PROJECT.supabase.co
-- SUPABASE_ANON_KEY=YOUR_ANON_KEY

create extension if not exists pgcrypto;

create table if not exists public.products (
  id text primary key,
  slug text unique not null,
  name text not null,
  label text,
  description text not null,
  price integer not null check (price >= 0),
  category text not null,
  items jsonb not null default '[]'::jsonb,
  is_custom boolean not null default false,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  images jsonb not null default '[]'::jsonb,
  seo jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.faqs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  answer text not null,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.content_pages (
  slug text primary key,
  title text,
  description text,
  body text,
  seo jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key,
  name text not null,
  phone text not null,
  city text not null,
  address text not null,
  items jsonb not null,
  subtotal integer not null,
  shipping integer not null,
  total integer not null,
  notes text not null default '',
  status text not null default 'awaiting_whatsapp_confirmation',
  source text not null default 'website',
  created_at timestamptz not null default now()
);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  page_path text,
  product_id text,
  payload jsonb not null default '{}'::jsonb,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.faqs enable row level security;
alter table public.site_settings enable row level security;
alter table public.content_pages enable row level security;
alter table public.orders enable row level security;
alter table public.site_events enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products" on public.products for select using (is_active = true);

drop policy if exists "Public can read active faqs" on public.faqs;
create policy "Public can read active faqs" on public.faqs for select using (is_active = true);

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings" on public.site_settings for select using (true);

drop policy if exists "Public can read active pages" on public.content_pages;
create policy "Public can read active pages" on public.content_pages for select using (is_active = true);

drop policy if exists "Public can insert orders" on public.orders;
create policy "Public can insert orders" on public.orders for insert with check (source = 'website');

drop policy if exists "Public can insert site events" on public.site_events;
create policy "Public can insert site events" on public.site_events for insert with check (true);

insert into public.site_settings (key, value) values
('siteUrl', '"https://5tap.ma"'),
('brandName', '"5Tap"'),
('tagline', '"5 étoiles, un seul tap"'),
('whatsappUrl', '"https://wa.me/212672606072"'),
('instagramUrl', '"https://www.instagram.com/5tap.ma/"'),
('defaultTitle', '"5Tap — Cartes de visite digitales et avis Google"'),
('defaultDescription', '"Cartes de visite digitales NFC personnalisées et supports avis Google dès 150 DH. Installation à Tanger et paiement à la livraison."'),
('currency', '"MAD"'),
('tangierShipping', '20'),
('moroccoShipping', '40'),
('metaPixelId', '""'),
('googleAnalyticsId', '""'),
('googleTagManagerId', '""')
on conflict (key) do update set value = excluded.value, updated_at = now();

insert into public.content_pages (slug, title, description, seo) values
('home', '5Tap — Cartes de visite digitales et avis Google', 'Cartes de visite digitales NFC personnalisées et supports avis Google dès 150 DH. Installation à Tanger et paiement à la livraison.', '{"canonicalPath":"/"}'),
('shop', 'Boutique NFC — Cartes et packs', 'Comparez les cartes et stands NFC 5Tap : 150 à 400 DH. Commande sans compte et paiement à la livraison partout au Maroc.', '{"canonicalPath":"/boutique"}'),
('faq', 'FAQ 5Tap', 'Réponses sur les cartes NFC, les avis Google, la livraison au Maroc et le paiement à la livraison.', '{"canonicalPath":"/faq"}'),
('contact', 'Contact 5Tap Tanger', 'Contactez 5Tap sur WhatsApp pour commander une carte NFC, un stand avis Google ou une démo à Tanger.', '{"canonicalPath":"/contact"}')
on conflict (slug) do update set title = excluded.title, description = excluded.description, seo = excluded.seo, updated_at = now();

insert into public.products (id, slug, name, label, description, price, category, items, is_custom, is_featured, sort_order, images, seo) values
('carte-google', 'carte-google', 'Carte Google Review', 'Le geste essentiel', 'Votre fiche Google à portée de main. Une carte à présenter à vos clients, où que vous soyez.', 150, 'cartes', '["1 carte NFC Google Review","Lien Google configuré","QR code en alternative"]', false, false, 10, '[{"url":"/product-concept.webp","alt":"Carte NFC Google Review 5Tap","width":1200,"height":800,"title":"Carte Google Review","metadata":{"source":"5Tap","type":"product"}}]', '{"title":"Carte Google Review NFC — 150 DH","description":"Carte NFC 5Tap pour ouvrir votre fiche Google et aider vos clients à laisser un avis.","canonicalPath":"/produit/carte-google"}'),
('essentiel', 'essentiel', 'Pack Essentiel', 'Pour bien démarrer', 'Le duo idéal pour votre comptoir : un stand visible et une carte toujours à portée de main.', 250, 'packs', '["1 stand standard","1 carte NFC Google Review","Configuration incluse"]', false, true, 20, '[{"url":"/product-concept.webp","alt":"Pack Essentiel NFC 5Tap","width":1200,"height":800,"title":"Pack Essentiel","metadata":{"source":"5Tap","type":"product"}}]', '{"title":"Pack Essentiel 5Tap — 250 DH","description":"Stand standard avec carte NFC Google Review, configuration incluse.","canonicalPath":"/produit/essentiel"}'),
('pro', 'pro', 'Pack Pro', 'Notre recommandation', 'Un stand à l’accueil, deux cartes en salle. Multipliez les occasions de recueillir un avis.', 300, 'packs', '["1 stand standard","2 cartes NFC Google Review","Configuration incluse"]', false, true, 30, '[{"url":"/product-concept.webp","alt":"Pack Pro NFC 5Tap","width":1200,"height":800,"title":"Pack Pro","metadata":{"source":"5Tap","type":"product"}}]', '{"title":"Pack Pro 5Tap — 300 DH","description":"Stand NFC et deux cartes Google Review pour restaurants, cafés, riads et commerces.","canonicalPath":"/produit/pro"}'),
('prestige', 'prestige', 'Pack Prestige', 'À votre image', 'Un stand premium personnalisé pour faire de chaque détail une signature de votre marque.', 400, 'packs', '["1 stand premium personnalisé","1 carte NFC Google Review","Personnalisation du stand avec votre logo"]', true, true, 40, '[{"url":"/product-concept.webp","alt":"Pack Prestige personnalisé 5Tap","width":1200,"height":800,"title":"Pack Prestige","metadata":{"source":"5Tap","type":"product"}}]', '{"title":"Pack Prestige personnalisé 5Tap — 400 DH","description":"Stand premium personnalisé avec logo et carte NFC Google Review.","canonicalPath":"/produit/prestige"}'),
('carte-visite', 'carte-visite', 'Carte de visite digitale NFC', 'Une rencontre. Une connexion.', 'Pour particuliers et professionnels : partagez votre profil digital, vos coordonnées et vos liens avec une carte NFC personnalisée à votre logo.', 150, 'cartes', '["1 carte NFC personnalisée","Votre logo et vos coordonnées","Profil de contact et liens configurés"]', true, false, 50, '[{"url":"/product-concept.webp","alt":"Carte de visite digitale NFC 5Tap","width":1200,"height":800,"title":"Carte de visite digitale NFC","metadata":{"source":"5Tap","type":"product"}}]', '{"title":"Carte de visite digitale NFC personnalisée — 150 DH","description":"Carte de visite NFC personnalisée avec logo, profil de contact, coordonnées et liens.","canonicalPath":"/produit/carte-visite"}')
on conflict (id) do update set
slug = excluded.slug,
name = excluded.name,
label = excluded.label,
description = excluded.description,
price = excluded.price,
category = excluded.category,
items = excluded.items,
is_custom = excluded.is_custom,
is_featured = excluded.is_featured,
sort_order = excluded.sort_order,
images = excluded.images,
seo = excluded.seo,
updated_at = now();
