export const whatsapp='https://wa.me/212672606072';
export const products=[
{id:'carte-google',name:'Carte Google Review',price:149,category:'cartes',label:'Le geste essentiel',desc:'Votre fiche Google à portée de main. Une carte à présenter à vos clients, où que vous soyez.',items:['1 carte NFC Google Review','Lien Google configuré','QR code en alternative'],custom:false},
{id:'essentiel',name:'Pack Essentiel',price:249,category:'packs',label:'Pour bien démarrer',desc:'Le duo idéal pour votre comptoir : un stand visible et une carte toujours à portée de main.',items:['1 stand standard','1 carte NFC Google Review','Configuration incluse'],custom:false},
{id:'pro',name:'Pack Pro',price:299,category:'packs',label:'Notre recommandation',desc:'Un stand à l’accueil, deux cartes en salle. Multipliez les occasions de recueillir un avis.',items:['1 stand standard','2 cartes NFC Google Review','Configuration incluse'],custom:false},
{id:'prestige',name:'Pack Prestige',price:399,category:'packs',label:'À votre image',desc:'Un stand premium personnalisé pour faire de chaque détail une signature de votre marque.',items:['1 stand premium personnalisé','1 carte NFC Google Review','Personnalisation du stand avec votre logo'],custom:true},
{id:'carte-visite',name:'Carte de visite digitale NFC',price:149,category:'cartes',label:'Une rencontre. Une connexion.',desc:'Pour particuliers et professionnels : partagez votre profil digital, vos coordonnées et vos liens avec une carte NFC personnalisée à votre logo.',items:['1 carte NFC personnalisée','Votre logo et vos coordonnées','Profil de contact et liens configurés'],custom:true},
];
export type Product=typeof products[number];
export type CartItem={id:string;quantity:number};
export const faqs=[
['Quelle différence entre une carte de visite NFC et une carte avis Google ?','La carte de visite digitale NFC partage votre profil de contact : coordonnées, site et réseaux sociaux. Elle est destinée aux particuliers et professionnels. La carte avis Google et les stands ouvrent la fiche Google d’un commerce pour permettre à ses clients de rédiger un avis. Choisissez le produit selon votre objectif.'],
['Comment fonctionne une carte NFC ?','La puce NFC transmet un lien lorsque le téléphone est approché de la carte ou du stand. Le client ouvre ce lien pour accéder à votre fiche Google ou à vos coordonnées. Le support n’a pas besoin de batterie. Une connexion Internet est nécessaire sur le téléphone.'],
['Avec quels téléphones est-elle compatible ?','Avec les téléphones équipés du NFC et capables de lire une URL, dont de nombreux iPhone et smartphones Android récents. Le NFC doit être activé si le téléphone le demande. La zone de lecture varie selon le modèle. Le QR code offre une alternative avec l’appareil photo.'],
['Le client doit-il installer une application ?','Non, aucune application 5Tap n’est nécessaire. Pour publier un avis Google, le client doit être connecté à son compte Google. Il reste libre de sa note et de son commentaire : aucun avis n’est publié automatiquement.'],
['Puis-je changer le lien plus tard ?','L’option dashboard à 79 DH/mois permet de gérer et de modifier votre lien sans remplacer le support. Elle est facultative et proposée séparément. Contactez-nous pour son activation et les fonctionnalités disponibles. Sans cette option, une modification peut nécessiter une reconfiguration du support.'],
['Quels sont les frais et délais de livraison ?','Livraison gratuite partout au Maroc. À Tanger : sous 24 h pour les produits standard et 48 h pour les cartes ou stands personnalisés. Ailleurs au Maroc : environ 4 jours. Pour une personnalisation, le délai court après validation du visuel. Les modalités sont confirmées avec vous sur WhatsApp.'],
['Comment se passe l’installation à Tanger ?','Nous configurons votre lien et vous accompagnons sur place dans la prise en main du support, sur rendez-vous à Tanger. L’installation est incluse. Ailleurs au Maroc, votre support est configuré avant son envoi.'],
['Quels modes de paiement acceptez-vous ?','Le paiement en espèces à la livraison est proposé pour votre commande. Aucun paiement en ligne n’est demandé sur ce site. Les frais de livraison sont affichés dans le récapitulatif avant validation.'],
['Comment personnaliser mon stand ou ma carte ?','Choisissez le Pack Prestige ou la carte de visite NFC, puis indiquez vos souhaits dans votre commande. Nous vous contacterons sur WhatsApp pour recevoir votre logo et valider le visuel avant la préparation.'],
];
